/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fff8f2',
        'surface-dim': '#e1d9cf',
        'surface-bright': '#fff8f2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fbf2e8',
        'surface-container': '#f5ede3',
        'surface-container-high': '#efe7dd',
        'surface-container-highest': '#e9e1d7',
        'on-surface': '#1e1b15',
        'on-surface-variant': '#48454f',
        'inverse-surface': '#343029',
        'inverse-on-surface': '#f8f0e5',
        outline: '#797580',
        'outline-variant': '#cac4d0',
        'surface-tint': '#62578c',
        primary: '#62578c',
        'on-primary': '#ffffff',
        'primary-container': '#9b8ec7',
        'on-primary-container': '#322658',
        'inverse-primary': '#ccbefa',
        secondary: '#6a577a',
        'on-secondary': '#ffffff',
        'secondary-container': '#edd4fe',
        'on-secondary-container': '#6d597d',
        tertiary: '#466368',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#7d9ba1',
        'on-tertiary-container': '#153337',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e7deff',
        'primary-fixed-dim': '#ccbefa',
        'on-primary-fixed': '#1e1244',
        'on-primary-fixed-variant': '#4a3f72',
        'secondary-fixed': '#f1dbff',
        'secondary-fixed-dim': '#d6bee7',
        'on-secondary-fixed': '#241433',
        'on-secondary-fixed-variant': '#523f61',
        'tertiary-fixed': '#c9e8ee',
        'tertiary-fixed-dim': '#adccd2',
        'on-tertiary-fixed': '#001f24',
        'on-tertiary-fixed-variant': '#2e4b50',
        background: '#fff8f2',
        'on-background': '#1e1b15',
        'surface-variant': '#e9e1d7',
        brand: {
          primary: '#9b8ec7',
          secondary: '#bda6ce',
          tertiary: '#b4d3d9',
          neutral: '#f2eae0',
          bg: '#fbf8f5',
          border: '#e5dcd0',
        }
      },
      boxShadow: {
        'ambient': '0 4px 20px rgba(155, 142, 199, 0.08)',
        'ambient-lg': '0 10px 40px rgba(155, 142, 199, 0.12)',
        'ambient-sm': '0 2px 10px rgba(155, 142, 199, 0.05)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 5px rgba(99, 102, 241, 0.3)' },
          '50%': { boxShadow: '0 0 20px rgba(99, 102, 241, 0.6)' },
        },
      },
    },
  },
  plugins: [],
};
